services:
  web-simulation-api:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: web-simulation-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - './logs/:/app/logs/'
    networks:
      - web_simulation_network
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

networks:
  web_simulation_network:
    name: web_simulation_network
    external: true
