services:
  # Service API
  web-simulation-api:
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    container_name: web-simulation-api
    env_file:
      - .env
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - web_simulation_network
    logging:
      driver: 'json-file'
      options:
        max-size: '100m'
        max-file: '5'

  # Service Loki
  web-simulation-loki:
    container_name: web-simulation-loki
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./docker/dev/loki-config.yml:/etc/loki/config.yml
    command: -config.file=/etc/loki/config.yml
    networks:
      - web_simulation_network

  # Service Promtail
  web-simulation-promtail:
    container_name: web-simulation-promtail
    image: grafana/promtail:2.9.0
    volumes:
      - ./docker/dev/promtail-config.yaml:/etc/promtail/promtail.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/log:/var/log
    command: -config.file=/etc/promtail/promtail.yaml
    networks:
      - web_simulation_network

  # Service Grafana
  web-simulation-grafana:
    container_name: web-simulation-grafana
    image: grafana/grafana:latest
    ports:
      - "3001:3000"
    volumes:
      - web_simulation_grafana_data:/var/lib/grafana
    depends_on:
      - web-simulation-loki
    networks:
      - web_simulation_network

volumes:
  web_simulation_grafana_data:

networks:
  web_simulation_network:
    name: web_simulation_network
    external: true
