compose-local-file=docker-compose.local.yml
compose-dev-file=docker-compose.dev.yml
compose-prod-file=docker-compose.prod.yml

app-container-local=web-simulation-api
app-container-dev=core_dev_api
app-container-prod=core_prod_api

local-logs:
	docker logs -f $(app-container-local)

# Local Command
local-deploy:
	docker compose -f $(compose-local-file) up -d --build  --remove-orphans --force-recreate

local-deploy-watch:
	docker compose -f $(compose-local-file) up --build  --remove-orphans --force-recreate

local-rebuild:
	docker compose -f $(compose-local-file) build --no-cache

local-down:
	docker compose -f $(compose-local-file) down

local-migrate:
	docker compose -f $(compose-local-file) exec $(app-container-local) yarn migration:run

local-seed:
	docker compose -f $(compose-local-file) exec $(app-container-local) yarn seed


# Dev Command
dev-deploy:
	docker compose -f $(compose-dev-file) up -d --build  --remove-orphans --force-recreate

dev-deploy-watch:
	docker compose -f $(compose-dev-file) up --build  --remove-orphans --force-recreate

dev-rebuild:
	docker compose -f $(compose-dev-file) build --no-cache

dev-down:
	docker compose -f $(compose-dev-file) down


# Prod Command
prod-deploy:
	docker compose -f $(compose-prod-file) up -d --build  --remove-orphans --force-recreate

prod-deploy-watch:
	docker compose -f $(compose-prod-file) up --build  --remove-orphans --force-recreate

prod-rebuild:
	docker compose -f $(compose-prod-file) build --no-cache

prod-down:
	docker compose -f $(compose-prod-file) down


# Check Log Local App Container
log-app-local:
	docker logs -f $(app-container-local)

# Check Log Development App Container
log-app-dev:
	docker logs -f $(app-container-dev)

# Check Log Production App Container
log-app-prod:
	docker logs -f $(app-container-prod)

# Create Migration On Local
create-migration:
	docker exec -it $(app-container-dev) yarn run typeorm-ts-node-commonjs migration:create ./src/database/migrations/$(migration-file)